### Create book-record
POST http://localhost:8080/api/v1/book-records/growth-plans/dbed1c15-daed-48c9-a475-08a6feed5dae
Content-Type: application/json
Authorization: {{authKey}}

{
  "title": "The Existentialist's Survival Guide: How to Live Authentically in an Inauthentic Age",
  "author": "Gordon Marino",
  "description": "Near the end of this book, Marino uses an apt metaphor, that reading about Kierkegaard, Sartre, Camus Nietsche, Dostoyevsky, Tolstoy, particularly Kierkegaard, is like mining for ore. There are veins of particularly rich meaning, and others that are more meager, and the accumulation that comes out of the mine depends upon many forays. "
}

### Get book-record by id
GET http://localhost:8080/api/v1/book-records/e54ad77b-d827-40f6-8191-0fd2e6670549
Content-Type: application/json
Authorization: {{authKey}}

